### ISSUE TITLE
zhmc_nic examples in documentation use zhmc_partition

### ISSUE THREAD

**Issue by jacobemery** [zhmcclient/zhmc-ansible-modules#1058]
**Describe the bug**
<-- A clear and concise description of what the bug is. -->
The examples for the zhmc_nic module in the documentation in Ansible Galaxy [here](https://galaxy.ansible.com/ui/repo/published/ibm/ibm_zhmc/content/module/zhmc_nic/) use the zhmc_partition module.

I know that "Note that the Ansible module zhmc_partition can be used to gather facts about existing NICs of a partition.", but the module parameters given in the examples don't work for the zhmc_partition module.

**Expected behavior**
<-- A clear and concise description of what you expected to happen. -->

The module's documentation should use its own module as the example, it should not reference other modules. The examples should work with the provided parameters.

**To Reproduce**
<-- Describe the steps to reproduce the behavior. -->
N/A

**Environment information**
* Output of `zhmc_prometheus_exporter --version`:
* HMC version:
N/A

**Ansible task**
<-- The Ansible task from the playbook or role that failed. -->

The provided example task fails, i.e:

```
- name: Gather facts about a NIC
      tags: nic_facts
      ibm.ibm_zhmc.zhmc_partition:
        hmc_host: "{{ hmc_host }}"
        hmc_auth: "{{ hmc_auth }}"
        cpc_name: "{{ cpc_name }}"
        partition_name: "{{ lpar_name }}"
        name: "{{ nic_name }}"
        state: facts
      register: nic_facts
```

with error:

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ibm.ibm_zhmc.zhmc_partition) module: partition_name. Supported parameters include: _faked_session, cpc_name, expand_crypto_adapters, expand_storage_groups, hmc_auth, hmc_host, log_file, name, properties, state."}`

Because the 'partition_name' in the example is not accepted by the zhmc_partition module, it should just be 'name'.

However, just by changing the module name to zhmc_nic, the provided example task succeeds:

```
    - name: "Gather facts about NIC {{ nic_name }}"
      tags: nic_facts
      ibm.ibm_zhmc.zhmc_nic:
        hmc_host: "{{ hmc_host }}"
        hmc_auth: "{{ hmc_auth }}"
        cpc_name: "{{ cpc_name }}"
        partition_name: "{{ lpar_name }}"
        name: "{{ nic_name }}"
        state: facts
      register: nic_facts_result
```

So I believe this should be a relatively simple fix, by just changing the module referenced in the examples to zhmc_nic.

**Log file**
<-- If possible, use the 'log_file' parameter in the Ansible task to create a log file and attach or paste the relevant parts of it. -->
