### ISSUE TITLE
Migrate to use delegate_to

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmc-ansible-modules#381]
Currently, the target host is localhost and the HMC is specified via module input parameters. This design is based on the capabilities of Ansible at the time the zhmc Ansible modules project started.

Meanwhile, Ansible supports a construct "delegate_to" which should allow specifying the HMCs as target hosts, delegating the execution of the runbooks to localhost.

This approach is incompatible for current users of the zhmc Ansible modules, and needs to be introduced either in a backwards compatible manner (preferred) or with a new major version.

**Comment by andy-maier** [comment]
Here is one way of doing it. It does not require changes to the zhmc modules at all and is therefore backwards compatible:

Playbook `module_facts_cpc.yml`:
```
- collections:
    - ibm.ibm_zhmc
  hosts:
    - myhmcs
  gather_facts: no
  vars_files:
    - vault.yml
  tasks:
    - name: "Get facts for CPC {{ cpc_name }}"
      zhmc_cpc:
        hmc_host: "{{ ansible_host }}"
        hmc_auth: "{{ hmc_auths[ansible_host] }}"
        name: "{{ cpc_name }}"
        state: facts
      delegate_to: localhost
      connection: local
      register: result
    - name: Print CPU and memory
      debug:
        msg: "HMC {{ ansible_host }}, CPC {{ cpc_name }}: CPU: {{ result.cpc['processor-count-ifl'] }} IFLs, memory: {{ result.cpc['storage-customer'] / 1024 }} GB"
```

Vault file `vaults.yml`:
```
hmc_auths:
  10.11.12.13:
    userid: myuser13
    password: mypassword13
  10.11.12.14:
    userid: myuser14
    password: mypassword14

cpc_name: mycpc  # does not need to be protected by a vault, it is just here to reduce number of files
```

Inventory file `inventory.yml`:
```
myhmcs:
  hosts:
    myhmc13:
      ansible_host: 10.11.12.13
    myhmc14:
      ansible_host: 10.11.12.14
```

Playbook invocations:
```
$ ansible-playbook -i inventory.yml module_facts_cpc.yml  # run against the default host list myhmcs=(myhmc13, myhmc14)
$ ansible-playbook -i inventory.yml module_facts_cpc.yml -l myhmc13  # run only against myhmc13
```

**Comment by ddimatos** [comment]
@andy-maier - some comments you might already know and a mixed use case to go with my comments.

* With non-ssh connection types, ie `connection: local` the connector can be used to deploy the playbook to the controller.
* With delegating tasks `delegate_to: localhost` the Ansible task is delegated to localhost.

Imagine a mixed use case where the majority of the work playbook should run on localhost (connection: local) defined at the top of the playbook:
```
- hosts: localhost
  connection: local
  ```
 there may be some tasks that need to be delegated to other hosts (`delegate_to: production.server.com`) where the production server is the source of truth and the playbook task is going to fetch a configuration file to be used with the zHMC playbook. This now might look like:
  
```
- hosts: localhost
  connection: local
  vars_files:
    - vault.yml
  vars:
    partition_name: sample-part-1
  collections:
    - ibm.ibm_zhmc
  tasks:
    - name: Fetch JSON config
      fetch:
        src: /var/configs/config.json
        dest: /tmp
        flat: true
        **delegate_to: production.server.com**
     - name: Display the JSON config
        shell: cat /tmp/config.json
        register: result
     - name: Save JSON config to a Variable
        set_fact:
          jsondata: "{{ result.stdout | from_json }}"
     #############################################################
     # Parse the jsondata and use it in the remaining playbook as the source of truth
     #############################################################
    - name: "Ensure partition {{ partition_name }} exists and is stopped"
      zhmc_partition:
        hmc_host: "{{ hmc_host }}"
        hmc_auth: "{{ hmc_auth }}"
        cpc_name: "{{ cpc_name }}"
        name: "{{ partition_name }}"
```

In the above case, defining  `connection: local` at the top is perfectly acceptable and overriding specific tasks to be delegated to that don't need to be run on localhost. All I am saying I think  `delegate_to: localhost` and`connection: local` are going to deliver the same result it appears to me thus I may have been premature in pointing out `delegate_to: localhost`, in the end, your controller still is localhost.
