### ISSUE TITLE
Unable to modify partition boot parameter to storage group

### ISSUE THREAD

**Issue by vmorris** [zhmcclient/zhmc-ansible-modules#640]
After creating a partition, I have modified it's boot option to be FTP, and this works great.
Once I've installed Linux into the partition, I want to change the boot option to the storage group, but I'm not finding much luck. For one, the documentation is not great.. but I think it should be supported. At least there's some indication in the release notes that support was added for this (I think!)...

I've tried using `boot_storage_volume_name` with both the URI string of the volume, and then name of the volume.

```yml
---
    - name: "Change boot device to volume"
      zhmc_partition:
        hmc_host: "{{ hmc_host }}"
        hmc_auth: "{{ hmc_auth }}"
        cpc_name: "{{ cpc_name }}"
        name: "{{ partition_name }}"
        state: stopped
        properties:
          boot_device: "storage-volume"
          boot_storage_volume_name: "{{ volume_name }}"
```

Results in:

```
"msg": "HTTPError: 400,6: The JSON object contains an unrecognized field ('boot-storage-volume-name') [POST /api/partitions/bd69cc5a-c1ce-11ed-9200-00106f23e4b1]"
```

I also tried using `boot_storage_volume` which resulted in:

```
"msg": "ParameterError: Property 'boot_storage_volume' is not allowed in the 'properties' module parameter."
```

Maybe this is just not fully enabled yet? Any ideas?

Thanks,
