### ISSUE TITLE
Support for redundant HMC hosts

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmc-ansible-modules#849]
PR https://github.com/zhmcclient/python-zhmcclient/pull/1371 (targeted for zhmcclient 1.13.0) introduces support for redundant HMCs by specifying a list of HMC hosts in the "host" init parameter of `zhmcclient.Session`.

The list of hosts can also be specified in the zhmcclient HMC inventory files, e.g.:
```
    M12:
      ansible_host:
        - "10.11.12.13"
        - "10.11.12.14"
```
That causes the zhmcclient testutils support to pass the list of hosts to `zhmcclient.Session`.

The ansible-playbook command does not complain about the list of hosts when specifying such a zhmcclient HMC inventory file as the Ansible inventory file, e.g.:
```
ansible-playbook -i inventory.yml -e hmc=M12 module_adapter_facts.yml 
```

However, the sample playbooks specify the host like this (and that is also likely done in real playbooks):
```
- hosts:
    - "{{ hmc | default('default') }}"  # HMC nickname from inventory entry
  gather_facts: no
  vars_files:
    - vault.yml
  vars:
    cpc: P0000M12
    adapter: sample-hs-1
    log_file: zhmc.log
  collections:
    - ibm.ibm_zhmc
  tasks:

    - name: "Get facts for adapter {{ adapter }} on CPC {{ cpc }}"
      delegate_to: localhost
      zhmc_adapter:
        hmc_host: "{{ ansible_host }}"      # passes the list as a string '["10.11.12.13", "10.11.12.14"]'
        hmc_auth: "{{ hmc_auth[inventory_hostname] }}"
        cpc_name: "{{ cpc }}"
        name: "{{ adapter }}"
        state: facts
        log_file: "{{ log_file | default(omit) }}"
      register: result
```

This issue is to fix that by adding support for detecting such a situation in the ibm_zhmc collection and by parsing that string back into a list.
