### ISSUE TITLE
Add the ability to query select properties for LPARs when in classic mode

### ISSUE THREAD

**Issue by mariahsarica** [zhmcclient/zhmc-ansible-modules#851]
When an HMC is in classic mode, currently you can only query the full list of properties rather than a subset. The full properties query is rather time consuming, especially when looping through a number of LPARs. I think it would be beneficial to add a way to only query the properties that you are interested in.

I looked through the WSAPI doc and the zhmcclient code, and I came up with a solution that I am using locally for now. I added an optional parameter to the `zhmc_lpar.py` module called select_properties which contains a list of LPAR properties to use with facts. In the `facts` function, I changed the following in the try block:

        if select_properties:
           lpar.pull_properties(select_properties)
        else:
           lpar.pull_full_properties()

Example:
```yaml
    - name: Get select properties of lpars
      zhmc_lpar:
        hmc_host: "{{ my_hmc_host }}"
        hmc_auth: "{{ session.hmc_auth }}"
        cpc_name: A89
        name: S5A
        state: facts
        select_properties: ['sysplex-name', 'os-name', 'cpc-name']
      register: lpar_facts
    
    - debug:
       msg: "{{ lpar_facts }}"
```

```
TASK [debug] **********************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "changed": false,
        "failed": false,
        "lpar": {
            "cpc-name": "A89",
            "name": "S5A",
            "object-uri": "/api/logical-partitions/943af48d-395d-3562-b50c-e8020e71bd89",
            "os-name": "S5A",
            "sysplex-name": "SVPLEX5"
        }
    }
}
```

I would be great if a solution similar to the above could be incorporated into the official support. Thanks for considering.
