### ISSUE TITLE
zhmc_user returning password when creating a user and updating the password

### ISSUE THREAD

**Issue by abhirams-1** [zhmcclient/zhmc-ansible-modules#967]
**Describe the bug**
zhmc_user module is returning 'password' parameter when creating a user and updating the password.

**Expected behavior**
'password' field should not be returned or it should be obscured.

**To Reproduce**
Run zhmc_user module with state="present" to create a user. For this operation, the 'password' is returned.
Now run zhmc_user module again with  state="present" and a different password to update the password of the user. For this operation too, the 'password' field is returned.

**Environment information**
* Output of `zhmc_prometheus_exporter --version`:
```
zhmc_prometheus_exporter version: 1.6.0
zhmcclient version: 1.14.0
```
* HMC version:
```
                "api-major-version": 4
                "api-minor-version": 10
                "hmc-version": "2.16.0"
```

**Ansible task**
```
ibm.ibm_zhmc.zhmc_user:
    hmc_host: "{{ hostname }}"
    hmc_auth: "{{ session.hmc_auth }}"
    name: "{{ params.name }}"
    state: "present"
    properties:
      description: "{{ params.fullname | default(omit) }}"
      authentication_type: "{{ params.auth_type | default(omit) }}"
      force_password_change: "{{ params.change_password | default(omit) }}"
      email_address: "{{ params.email | default(omit) }}"
      ldap_server_definition_name: "{{ params.ldap_server | default(omit) }}"
      password: "{{ params.password | default(omit) }}"
      password_rule_name: "{{ params.password_rule | default(omit) }}"
      user_role_names: "{{ params.hmc_roles | default(omit) }}"
      type: "{{ params.hmc_type | default('standard') }}"
      disabled: "{{ omit if params.user_state is not defined else ( false if params.user_state == 'enabled' else ( true if params.user_state == 'disabled' else omit ) ) }}"
      allow_management_interfaces: true
      allow_remote_access: true
    log_file: "{{ log_file }}"
```

**Log file**
<-- If possible, use the 'log_file' parameter in the Ansible task to create a log file and attach or paste the relevant parts of it. -->
